"""baglab - ROS2 rosbag data analysis library."""

from baglab import plot as plot
from baglab.plot import plot_error_band, plot_step_response, plot_timeseries, plot_xy_trajectory
from baglab.analysis import delay_estimate, stepinfo, tracking_error
from baglab.diagnostics import latency_chain, message_gaps, topic_delay, topic_rate
from baglab.io import MsgAccessor, FieldGroup, align_origin, clear_cache, explode_array, find_time, load, recv_time_to_sec, reindex_by_stamp, stamp_to_sec, time_slice
from baglab.signal import diff, fft, integrate, lowpass, moving_average
from baglab.stats import describe, rms
from baglab.geometry import (
    align_time,
    angle_diff,
    cumulative_distance,
    distance_2d,
    distance_3d,
    interp_pose,
    match_by_time,
    normalize_angle,
    pose_error,
    pose_to_xyyaw,
    quat_to_rpy,
    quat_to_yaw,
    resample,
    rpy_to_quat,
    to_numpy_2d,
    to_numpy_3d,
    to_xy,
    to_xyz,
    twist_to_speed,
    twist_to_speed_2d,
    unwrap,
    velocity_from_pose,
    yaw_rate_from_pose,
    yaw_to_quat,
)

__all__ = [
    "MsgAccessor",
    "FieldGroup",
    "align_origin",
    "clear_cache",
    "explode_array",
    "find_time",
    "load",
    "recv_time_to_sec",
    "reindex_by_stamp",
    "stamp_to_sec",
    "time_slice",
    "align_time",
    "angle_diff",
    "cumulative_distance",
    "distance_2d",
    "distance_3d",
    "interp_pose",
    "match_by_time",
    "normalize_angle",
    "pose_error",
    "pose_to_xyyaw",
    "quat_to_rpy",
    "quat_to_yaw",
    "resample",
    "rpy_to_quat",
    "to_numpy_2d",
    "to_numpy_3d",
    "to_xy",
    "to_xyz",
    "twist_to_speed",
    "twist_to_speed_2d",
    "unwrap",
    "velocity_from_pose",
    "yaw_rate_from_pose",
    "yaw_to_quat",
    "describe",
    "rms",
    "diff",
    "fft",
    "integrate",
    "lowpass",
    "moving_average",
    "delay_estimate",
    "stepinfo",
    "tracking_error",
    "latency_chain",
    "message_gaps",
    "topic_delay",
    "topic_rate",
    "plot_error_band",
    "plot_step_response",
    "plot_timeseries",
    "plot_xy_trajectory",
]
